# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

desc "Deploy test version to Firebase"
lane :upload_debug_apk_to_firebase do
  firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    apk_path: "./app-debug.apk",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
  )
end

desc "Deploy staging version to Firebase"
lane :upload_staging_apk_to_firebase do
  firebase_app_distribution(
    app: ENV["FIREBASE_APP_ID"],
    apk_path: "./app-staging-unsigned-signed.apk",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
  )
end

desc "Deploy release version to Play Console"
lane :deploy_release do
  gradle(
    task: "bundle",
    build_type: "release",
    properties: {
      "android.injected.signing.store.file" => ENV["KEYSTORE_FILE"],
      "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
      "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
      "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
    }
  )

  upload_to_play_store(
    track: "internal",
    json_key: ENV["PLAY_SERVICE_ACCOUNT_KEY"]
  )
end
