name: Build and Deploy Release AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java and Gradle
        uses: ./.github/actions/setup
      - name: Set build number
        run: echo "BUILD_NUMBER=$(( ${{ github.run_attempt }} - 1 + ${{ github.run_number }} ))" >> $GITHUB_ENV
      - name: Print Build Number
        run: echo "Build Number $BUILD_NUMBER"
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1.205.0
        with:
          ruby-version: '3.0.0'
          bundler-cache: true # Automatically installs Bundler and caches gems
      - name: Install Dependencies
        run: bundle install
      - name: Decode Service Account Key JSON File
        uses: timheuer/base64-to-file@v1
        id: service_account_json_file
        with:
          fileName: "serviceAccount.json"
          encodedString: ${{ secrets.PLAY_SERVICE_ACCOUNT_KEY }}
      - name: Decode Keystore File
        uses: timheuer/base64-to-file@v1
        id: android_keystore
        with:
          fileName: "android_keystore.keystore"
          encodedString: ${{ secrets.KEYSTORE_FILE }}
      - name: Build and Deploy Android release
        run: bundle exec fastlane deploy_release
        env:
          KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          PLAY_SERVICE_ACCOUNT_KEY: ${{ steps.service_account_json_file.outputs.filePath }}